### ISSUE TITLE
Expose dependencies in manifest

### ISSUE THREAD

**Issue by kubeliv** [GayPizzaSpecifications/concrete#7]
If a plugin depends on another, it'd be nice to expose this dependency in the manifest, so that the installation script or update logic can handle this situation. A temporary hack could explicitly install the core first and ask for the remaining plugins, but I don't think we should require any plugin except the core even if the plugin bails out and doesn't do anything.

**Comment by azenla** [comment]
@kubeliv 

This has been implemented via a new extensible manifest format. Concrete Bukkit plugins must specify dependencies explicitly, which will be mapped to items inside the manifest:

```kotlin
plugin {
  dependency(project(":foundation-core"))
}
```

The reason this isn't auto-detected is that plugin dependencies != Gradle dependencies, and especially in Foundation where foundation-core is exported via an intermediate library, it's not really easily detectable.

Example manifest:
```json
{
  "items": [
    {
      "name": "foundation-bifrost",
      "type": "bukkit-plugin",
      "version": "0.2.51",
      "dependencies": [
        "foundation-core"
      ],
      "files": [
        {
          "name": "foundation-bifrost-0.2.51-plugin.jar",
          "type": "plugin-jar",
          "path": "foundation-bifrost/build/libs/foundation-bifrost-0.2.51-plugin.jar"
        }
      ]
    },
    {
      "name": "foundation-core",
      "type": "bukkit-plugin",
      "version": "0.2.51",
      "dependencies": [],
      "files": [
        {
          "name": "foundation-core-0.2.51-plugin.jar",
          "type": "plugin-jar",
          "path": "foundation-core/build/libs/foundation-core-0.2.51-plugin.jar"
        }
      ]
    }
  ]
}
```

See https://artifacts.gay.pizza/foundation/manifest.json for the full manifest in action on Foundation.

install.sh and the update mechanism in Foundation need to be updated to support the new format. This work is not complete. Please note that the manifest is no longer in build/manifests when upload, it is now just manifest.json at the root. This is because the paths inside the JSON for downloading files are relative to the URL of the manifest.json.

manifest.json is extensible in that all parsers should assume extra fields may be present.

It is also possible in a future release of Concrete to support bundling tools, hence the `type` field. Foundation's new update code should likely only handle items of type `bukkit-plugin` and only download files of type `plugin-jar`.

**Comment by azenla** [comment]
Update engine support is now implemented in Foundation: https://github.com/GayPizzaSpecifications/foundation/commit/90690666c5d7f07fb97191bd23f39b30d0c6969a
